version: "3.4"
services: 
  swecvi:
    image: swecvi_release_stage
    ports:
      - 8090:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
      - CONNECTION_STRING=Server=172.28.0.3,1433;Database=coreDbSwecvi;User ID=sa;Password=Asdfgh1@3;TrustServerCertificate=True
      - HOSPITAL_CONNECTION_STRING=Server=172.28.0.3,1433;Database=coreDbSwecviHospital;User ID=sa;Password=Asdfgh1@3;TrustServerCertificate=True
      - ADMIN_CONNECTION_STRING=Server=172.28.0.3,1433;Database=coreDbSwecviAdmin;User ID=sa;Password=Asdfgh1@3;TrustServerCertificate=True
  swecvi_mirthconnect:
    image: swecvi_minthconnect_release_stage
    ports:
      - 8098:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
      - ADMIN_CONNECTION_STRING=Server=172.28.0.3,1433;Database=coreDbSwecviAdmin;User ID=sa;Password=Asdfgh1@3;TrustServerCertificate=True

  
